# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: ci-analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
